name: Build and Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read
  
jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install modules dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest build wheel poetry

      - name: Install python dependencies
        run: |
          poetry install --no-root

      - name: Install node and typescript
        run: |
          npm install

      - name: Build package
        run: python3 build.py

      - name: List folder
        run: ls -la static 

      - name: List tar files
        run: tar -tvf dist/home_assistant_eltako_frontend-0.0.3.tar.gz

      - name: list whl files
        run: zip -sf dist/home_assistant_eltako_frontend-0.0.3-py2.py3-none-any.whl

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          username: __token__
          password: ${{ secrets.PYPI_TOKEN }} 